AWSTemplateFormatVersion: '2010-09-09'
Description: DNS CloudFront

Parameters:
  EnvironmentName:
    Type: String

  DomainName:
    Type: String

  HostedZoneName:
    Type: String
    Default: inhesta.net.

Resources:
  DNSA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-cf-domain"
        HostedZoneId: Z2FDTNDATAQYW2

  DNSAAAA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Ref DomainName
      Type: AAAA
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: "${EnvironmentName}-cf-domain"
        HostedZoneId: Z2FDTNDATAQYW2
